name: Validate Top-Up Request
description: Find and validate BSV address in an issue
outputs:
  is_valid:
    description: Indicates whether the issue is valid (contains exactly one BSV address).
  address:
    description: The valid BSV address if found, otherwise empty.
runs:
  using: "composite"
  steps:
    - name: Validate BSV Address
      shell: bash
      run: |
        echo "::group::Logs"
        echo "Searching for BSV address in issue body..."
        MATCHES=$(echo "${ISSUE_BODY}" | grep -oE '\b1[a-km-zA-HJ-NP-Z0-9]{26,35}\b' || echo "")
        echo "Matches: $MATCHES"
        
        if [ -z "$MATCHES" ]; then
            MATCH_COUNT=0
        else
          MATCH_COUNT=$(echo "$MATCHES" | wc -l)
        fi
        echo "Found $MATCH_COUNT matches."
        
        if [ "$MATCH_COUNT" -eq 1 ]; then
          ADDRESS=$(echo "$MATCHES" | head -n 1)
          echo "Address found: $ADDRESS"
          gh issue comment -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --body "The following BSV address was found in this issue: `$ADDRESS`"
          gh issue edit -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --add-label "topup_request"
        
          hasLabel=$(gh issue view -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --json labels --jq '.labels[].name' | grep -q "invalid" && echo "true" || echo "false")
          if [ "$hasLabel" = "true" ]; then
            echo "removing label 'invalid'"
            gh issue edit -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --remove-label "invalid"
          fi
        
          echo "is_valid=true" >> $GITHUB_OUTPUT
          echo "address=$ADDRESS" >> $GITHUB_OUTPUT
          echo "::endgroup::"
          exitCode=0
        elif [ "$MATCH_COUNT" -gt 1 ]; then
          echo "Too many addresses found: $MATCHES"
          COMMENT_BODY="This issue is invalid because it contains too many BSV addresses:\n\n$MATCHES"
          gh issue comment -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --body "$COMMENT_BODY"
          gh issue edit -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --add-label "invalid"
        
          hasLabel=$(gh issue view -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --json labels --jq '.labels[].name' | grep -q "topup_request" && echo "true" || echo "false")
          if [ "$hasLabel" = "true" ]; then
            echo "removing label 'topup_request'"
            gh issue edit -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --remove-label "topup_request"
          fi
        
          echo "is_valid=false" >> $GITHUB_OUTPUT
          echo "address=" >> $GITHUB_OUTPUT
          echo "::endgroup::"
          exitCode=113
        else
          echo "No valid addresses found."
          gh issue comment -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --body "This issue is invalid because it contains no valid BSV addresses."
          gh issue edit -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --add-label "invalid"
        
          hasLabel=$(gh issue view -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --json labels --jq '.labels[].name' | grep -q "topup_request" && echo "true" || echo "false")
          if [ "$hasLabel" = "true" ]; then
            echo "removing label 'topup_request'"
            gh issue edit -R "$GITHUB_REPOSITORY" "${ISSUE_NUMBER}" --remove-label "topup_request"
          fi
        
          echo "is_valid=false" >> $GITHUB_OUTPUT
          echo "address=" >> $GITHUB_OUTPUT
          echo "::endgroup::"
          exitCode=113
        fi
        
        echo "::group::Outputs"
        cat $GITHUB_OUTPUT
        echo "::endgroup::"
        exit $exitCode
